echo Running linux configuration...
# install dependencies...
sudo apt install -y libglfw3 libvulkan-dev libglm-dev libtinyobjloader-dev libstb-dev libspdlog-dev nlohmann-json3-dev
# install github submodules...
git submodule init ../Agos/vendor/EventBus
git submodule update ../Agos/vendor/EventBus
